version: "3.3"

services:
  gateway:
    image: "nestjs-marsy/gateway"
    restart: always
    ports:
      - 9500:3000
    environment:
      - MARSY_LAUNCHPAD_SERVICE_URL_WITH_PORT=${MARSY_LAUNCHPAD_SERVICE}:3000
      - MARSY_WEATHER_SERVICE_URL_WITH_PORT=${MARSY_WEATHER_SERVICE}:3000
      - MARSY_MISSION_SERVICE_URL_WITH_PORT=${MARSY_MISSION_SERVICE}:3000
      - MARSY_MOCK_SERVICE_URL_WITH_PORT=${MARSY_MOCK_SERVICE}:3000
      - MARSY_TELEMETRY_SERVICE_URL_WITH_PORT=${MARSY_TELEMETRY_SERVICE}:3000
    networks:
        - nestjs-marsy-network
networks:
  nestjs-marsy-network:
    driver: bridge