version: "3.3"

services:
  broadcast-service:
    image: "nestjs-marsy/broadcast-service"
    restart: always
    ports:
      - 3021:3000
    networks:
      - nestjs-marsy-network
    external_links:
      - docker-compose-kafka-service:kafka-service:kafka-service

networks:
  nestjs-marsy-network:
    driver: bridge