version: "3.3"

services:
  marsy-mission-service:
    image: "nestjs-marsy/marsy-mission"
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongo_db_marsy_mission
    environment:
      - MARSY_LAUNCHPAD_URL_WITH_PORT=${MARSY_LAUNCHPAD_SERVICE}:3000
      - MARSY_WEATHER_URL_WITH_PORT=${MARSY_WEATHER_SERVICE}:3000
    external_links:
      - docker-compose-kafka-service:kafka-service:kafka-service
    networks:
      - nestjs-marsy-network
  mongo_db_marsy_mission:
    image: "mongo:4.4.15"
    restart: always
    ports:
      - 27017:27017
    networks:
      - nestjs-marsy-network
    logging:
      driver: none
networks:
  nestjs-marsy-network:
    driver: bridge