version: "3.3"

services:
  marsy-booster-service:
    image: "nestjs-marsy/marsy-boostercontrol"
    restart: always
    ports:
      - 3030:3000
    environment:
      - MARSY_MOCK_SERVICE_URL_WITH_PORT=${MARSY_MOCK_SERVICE}:3000
      - MARSY_MISSION_SERVICE_URL_WITH_PORT=${MARSY_MISSION_SERVICE}:3000
    networks:
      - nestjs-marsy-network
    external_links:
      - docker-compose-kafka-service:kafka-service:kafka-service
networks:
  nestjs-marsy-network:
    driver: bridge