version: "3.3"

services:
  marsy-launchpad-service:
    image: "nestjs-marsy/marsy-launchpad"
    restart: always
    ports:
      - 3001:3000
    depends_on:
      - mongo_db_marsy_launchpad
    environment:
      - MARSY_MISSION_SERVICE_URL_WITH_PORT=${MARSY_MISSION_SERVICE}:3000
      - MARSY_MOCK_SERVICE_URL_WITH_PORT=${MARSY_MOCK_SERVICE}:3000
      - MARSY_GUIDANCE_SERVICE_URL_WITH_PORT=${MARSY_GUIDANCE_SERVICE}:3000
    networks:
      - nestjs-marsy-network
    external_links:
      - docker-compose-kafka-service:kafka-service:kafka-service
  mongo_db_marsy_launchpad:
    image: "mongo:4.4.15"
    restart: always
    ports:
      - 27019:27017
    networks:
      - nestjs-marsy-network
    logging:
      driver: none
networks:
  nestjs-marsy-network:
    driver: bridge