name: Production

on:
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  integration:
    name: Microserices integration tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2 

      - name: "building services"
        shell: bash
        run: |
          ./build-all.sh

      - name: "installing dependencies"
        shell: bash
        run: |
          cd ./integration-tests
          npm install

      - name: "running integration tests"
        shell: bash
        run: |
          pwd | cat
          ls | cat
          npm i -g jest
          ./run-local-integrationtest.sh
